[package]
name = "calculate"
version = "0.1.0"
edition = "2021"

[dependencies]
smolcalc = { path = "../", features = ["num_complex", "num_rational"] }
num-bigint = "0.4.4"
num-rational = "0.4.1"
num-complex = "0.4.6"
num-traits = "0.2.19"
